version: 2
jobs:
  build:  
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - setup_remote_docker
#   deploy:
#     staging:
#       branch: master
#       codedeploy:
#         AWSTutorial:
#           deployment_group:CodeDeployGroup    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
#       - deploy
