
version: 2
jobs:
  build:  
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - setup_remote_docker
   deploy:
    staging:
      branch: master
      codedeploy:
        AWSTutorial:
          application_root: /var/www/html
          region: us-east-1
          revision_location:
            revision_type: S3
            s3_location:
              bucket: my-bucket
              key_pattern: AWSTutorial-{BRANCH}-{SHORT_COMMIT}
          deployment_group: Ec2CodeDeployGroup     
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy
